version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - proxy-pool-data:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  proxy-pool-data:
    driver: local